[project]
name = "rsovs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.9",
    "nvmpy>=0.2.4",
    "open-clip-torch>=3.3.0",
    "torchaudio==2.4.1",
    "torchvision==0.19.1",
    "transformers==4.35.2",
    "ultralytics>=8.4.62",
    "kornia>=0.8.3",
    "scikit-learn>=1.9.0",
    "einops>=0.8.2",
    "jsonargparse>=4.49.0",
    "omegaconf>=2.3.1",
    "tensorboard>=2.20.0",
    "pydensecrf2>=1.1",
    "uplift[vit]",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu121"

[[tool.uv.index]]
name = "aliyun-pytorch"
url = "https://mirrors.nju.edu.cn/pytorch/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "aliyun-pytorch" }
uplift = { git = "https://github.com/mwalmer-umd/UPLiFT.git" }
